# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_appointment_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
