# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_need_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='need_string',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
