# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-08 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170201_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.DateField(default=datetime.datetime(2017, 2, 8, 18, 19, 18, 87432, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
