# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 10:38
from __future__ import unicode_literals

from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_need_need_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='duration_heal',
            field=models.DurationField(default=timedelta(minutes=30)),
            preserve_default=False,
        ),
    ]
