# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-25 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0004_need_duration_heal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Nurse')),
            ],
        ),
        migrations.AddField(
            model_name='need',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Appointment'),
        ),
    ]
