# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-11 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170208_1819'),
        ('event', '0005_auto_20170211_1037'),
    ]

    operations = [
    ]
