# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170125_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Nurse'),
        ),
    ]
