# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-18 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='availability_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='availability.AvailabilityGroup'),
        ),
        migrations.AddField(
            model_name='availability',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Nurse'),
        ),
    ]
