# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygroup',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Nurse'),
        ),
        migrations.AddField(
            model_name='availability',
            name='availability_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='availability.AvailabilityGroup'),
        ),
    ]
