# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-18 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='nurse',
        ),
        migrations.AddField(
            model_name='availabilitygroup',
            name='frequency',
            field=models.CharField(choices=[('U', 'Unique'), ('D', 'Tous les jours'), ('W', 'Toutes les semaines')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabilitygroup',
            name='nurse',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.Nurse'),
            preserve_default=False,
        ),
    ]
