# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_availabilitygroup_nurse'),
        ('availability', '0002_auto_20170115_1341'),
    ]

    operations = [
    ]
