# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20161212_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Person')),
                ('information', models.CharField(max_length=255)),
            ],
            bases=('user.person',),
        ),
    ]
