# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-17 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='id',
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.CharField(default='Paris', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='postcode',
            field=models.IntegerField(default=98765),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
