# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20161212_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='Paris', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='postcode',
            field=models.IntegerField(default=75001),
            preserve_default=False,
        ),
    ]
